export const json = {
  0: {
    Tasknumber: "4-1",
    Name: "Demolish rickety bridge",
    "Available after": "Level 9",
    "Opens Task": "4-2",
    "Items Needed": "Axe,\u00a0Crowbar",
    Rewards: "3 XP,\u00a0Energy Chest",
  },
  1: {
    Tasknumber: "4-2",
    Name: "Lay new foundations",
    "Available after": "4-1",
    "Opens Task": "4-3, 4-8",
    "Items Needed": "Mallet, Wood (IV)",
    Rewards: "1 XP",
  },
  2: {
    Tasknumber: "4-3",
    Name: "Place planking",
    "Available after": "4-2",
    "Opens Task": "4-4",
    "Items Needed": "3 Wood (IV)",
    Rewards: "1 XP",
  },
  3: {
    Tasknumber: "4-4",
    Name: "Install footboards",
    "Available after": "4-3",
    "Opens Task": "4-5, 4-6",
    "Items Needed": "Pliers,\u00a0Box of Screws",
    Rewards: "8 XP,\u00a0Green Box",
  },
  4: {
    Tasknumber: "4-5",
    Name: "Restore pool 3",
    "Available after": "4-4",
    "Opens Task": "-",
    "Items Needed": "Spade,\u00a0Gardening Gloves (II)",
    Rewards: "3 XP,\u00a0Bronze Coin Chest",
  },
  5: {
    Tasknumber: "4-6",
    Name: "Paint bridge",
    "Available after": "4-4",
    "Opens Task": "4-7",
    "Items Needed": "Paint Brush,\u00a0Paint Can (II)",
    Rewards: "8 XP",
  },
  6: {
    Tasknumber: "4-7",
    Name: "Install lights 1",
    "Available after": "4-6",
    "Opens Task": "-",
    "Items Needed": "2 Post Lights (IV)",
    Rewards: "1 XP,\u00a0Green Box",
  },
  7: {
    Tasknumber: "4-8",
    Name: "Restore path 1",
    "Available after": "4-2",
    "Opens Task": "4-9, 4-18",
    "Items Needed": "Spade,\u00a0Gardening Gloves (II)",
    Rewards: "3 XP",
  },
  8: {
    Tasknumber: "4-9",
    Name: "Trim lawn 1",
    "Available after": "4-8",
    "Opens Task": "4-10",
    "Items Needed": "Hedge Shears",
    Rewards: "8 XP,\u00a0Fancy Blue Chest (I)",
  },
  9: {
    Tasknumber: "4-10",
    Name: "Remove moss 1",
    "Available after": "4-9",
    "Opens Task": "4-11, 4-13",
    "Items Needed": "Garden Fork,\u00a0Gardening Gloves (II)",
    Rewards: "1 XP,\u00a0Simple Brown Box",
  },
  10: {
    Tasknumber: "4-11",
    Name: "Restore pool 1",
    "Available after": "4-10",
    "Opens Task": "4-12",
    "Items Needed": "Spade,\u00a0Gardening Gloves (II)",
    Rewards: "1 XP",
  },
  11: {
    Tasknumber: "4-12",
    Name: "Plant flowers 1",
    "Available after": "4-11",
    "Opens Task": "-",
    "Items Needed": "2 Orange Flowers",
    Rewards: "3 XP",
  },
  12: {
    Tasknumber: "4-13",
    Name: "Prune tree 1",
    "Available after": "4-10",
    "Opens Task": "4-14",
    "Items Needed": "Hedge Shears",
    Rewards: "8 XP,\u00a0Brown Chest (I)",
  },
  13: {
    Tasknumber: "4-14",
    Name: "Remove moss 2",
    "Available after": "4-13",
    "Opens Task": "4-15, 4-16",
    "Items Needed": "Garden Fork,\u00a0Gardening Gloves (II)",
    Rewards: "1 XP",
  },
  14: {
    Tasknumber: "4-15",
    Name: "Prune tree 2",
    "Available after": "4-14",
    "Opens Task": "-",
    "Items Needed": "Hedge Shears",
    Rewards: "3 XP,\u00a0Fancy Blue Chest (I)",
  },
  15: {
    Tasknumber: "4-16",
    Name: "Restore pool 2",
    "Available after": "4-14",
    "Opens Task": "4-17",
    "Items Needed": "Spade,\u00a0Gardening Gloves (II)",
    Rewards: "3 XP,\u00a0Simple Brown Box",
  },
  16: {
    Tasknumber: "4-17",
    Name: "Plant flowers 2",
    "Available after": "4-16",
    "Opens Task": "-",
    "Items Needed": "2 Orange Flowers",
    Rewards: "3 XP",
  },
  17: {
    Tasknumber: "4-18",
    Name: "Restore path 2",
    "Available after": "4-8",
    "Opens Task": "4-19",
    "Items Needed": "Spade,\u00a0Gardening Gloves (II)",
    Rewards: "3 XP,\u00a0Energy Chest",
  },
  18: {
    Tasknumber: "4-19",
    Name: "Remove fallen tree",
    "Available after": "4-18",
    "Opens Task": "4-20",
    "Items Needed": "Axe",
    Rewards: "1 XP",
  },
  19: {
    Tasknumber: "4-20",
    Name: "Demolish rickety stairs",
    "Available after": "4-19",
    "Opens Task": "4-21",
    "Items Needed": "Axe,\u00a0Hammer",
    Rewards: "3 XP,\u00a0Brown Chest (I)",
  },
  20: {
    Tasknumber: "4-21",
    Name: "Lay new foundations",
    "Available after": "4-20",
    "Opens Task": "4-22",
    "Items Needed": "Mallet,2 Wood (IV)",
    Rewards: "1 XP",
  },
  21: {
    Tasknumber: "4-22",
    Name: "Place treads",
    "Available after": "4-21",
    "Opens Task": "4-23",
    "Items Needed": "3 Wood (IV)",
    Rewards: "1 XP",
  },
  22: {
    Tasknumber: "4-23*",
    Name: "Install risers",
    "Available after": "4-22",
    "Opens Task": "4-24, 4-27, 4-32, 5-1",
    "Items Needed": "Pliers,\u00a0Box of Screws",
    Rewards: "3 XP,\u00a0Green Box",
  },
  23: {
    Tasknumber: "4-24",
    Name: "Trim lawn 2",
    "Available after": "4-23",
    "Opens Task": "4-25",
    "Items Needed": "Hedge Shears",
    Rewards: "3 XP,\u00a0Fancy Blue Chest (I)",
  },
  24: {
    Tasknumber: "4-25",
    Name: "Remove moss 3",
    "Available after": "4-24",
    "Opens Task": "4-26",
    "Items Needed": "Garden Fork,\u00a0Gardening Gloves (II)",
    Rewards: "1 XP",
  },
  25: {
    Tasknumber: "4-26",
    Name: "Restore pool 4",
    "Available after": "4-25",
    "Opens Task": "-",
    "Items Needed": "Spade,\u00a0Gardening Gloves (II)",
    Rewards: "1 XP,\u00a0Simple Brown Box",
  },
  26: {
    Tasknumber: "4-27",
    Name: "Paint stairs",
    "Available after": "4-23",
    "Opens Task": "4-28",
    "Items Needed": "Paint Brush,\u00a0Paint Can (II)",
    Rewards: "1 XP",
  },
  27: {
    Tasknumber: "4-28",
    Name: "Install lights 2",
    "Available after": "4-27",
    "Opens Task": "4-29",
    "Items Needed": "4 Post Lights (IV)",
    Rewards: "8 XP,\u00a0Fancy Blue Chest (I)",
  },
  28: {
    Tasknumber: "4-29",
    Name: "Plant flowers 3",
    "Available after": "4-28",
    "Opens Task": "4-30",
    "Items Needed": "3 Orange Flowers",
    Rewards: "8 XP,\u00a0Bronze Coin Chest",
  },
  29: {
    Tasknumber: "4-30",
    Name: "Plant flowers 5",
    "Available after": "4-29",
    "Opens Task": "4-31",
    "Items Needed": "2 Orange Flowers",
    Rewards: "3 XP,Blue Box",
  },
  30: {
    Tasknumber: "4-31",
    Name: "Restore water flow",
    "Available after": "4-30",
    "Opens Task": "-",
    "Items Needed": "Adjustable Wrench,\u00a0Hammer",
    Rewards: "50 XP,\u00a0Fancy Blue Chest (I)",
  },
  31: {
    Tasknumber: "4-32",
    Name: "Plant flowers 4",
    "Available after": "4-23",
    "Opens Task": "4-33",
    "Items Needed": "2 Orange Flowers",
    Rewards: "1 XP",
  },
  32: {
    Tasknumber: "4-33",
    Name: "Prune tree 3",
    "Available after": "4-32",
    "Opens Task": "4-34",
    "Items Needed": "Hedge Shears",
    Rewards: "8 XP,\u00a0Brown Chest (I)",
  },
  33: {
    Tasknumber: "4-34*",
    Name: "Remove overgrowth",
    "Available after": "4-33",
    "Opens Task": "4-35",
    "Items Needed": "Hedge Shears",
    Rewards: "3 XP,\u00a0Energy Chest",
  },
  34: {
    Tasknumber: "4-35",
    Name: "Clean up 1",
    "Available after": "4-34",
    "Opens Task": "4-36",
    "Items Needed": "Knife,\u00a0Gardening Gloves (II)",
    Rewards: "1 XP,\u00a0Simple Brown Box",
  },
  35: {
    Tasknumber: "4-36",
    Name: "Clean up 2",
    "Available after": "4-35",
    "Opens Task": "4-37",
    "Items Needed": "Brush,\u00a0Gardening Gloves (II)",
    Rewards: "3 XP",
  },
  36: {
    Tasknumber: "4-37*",
    Name: "Install eyes",
    "Available after": "4-36",
    "Opens Task": "-",
    "Items Needed": "Sponge,\u00a0Liquid Soap",
    Rewards: "8 XP",
  },
};
